name: ninjaz_posts_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.0
  iconly: ^1.0.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.6
  timeago: ^3.6.1
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.3
  test: ^1.24.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
