name: Flutter CI

on:
  pull_request:
    branches: [master]

env:
  flutter_version: "3.19.0"

jobs:
  build-android:
    # if: ${{ github.event.pull_request.merged }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache of dart pub get dependencies
          flutter-version: ${{ env.flutter_version }}
            
      - name: Get dependencies
        run: flutter pub get

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'
      
      - name: Run tests
        run: dart run realm_dart install && flutter test && flutter test integration_test

      - name: Build APK
        id: build
        run: flutter build apk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: build/app/outputs/flutter-apk/*.apk
      
      - name: Send Email
        uses: cinotify/github-action@main
        with:
          to: 'topia.amr@icloud.com'
          subject: 'GitHub Actions Job Status'
          body:  'Job ${{ github.job }} finished! \n \n See the results here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \n \n from: NinjazPosts App'
      
      - name: Send Another Email Copy
        uses: cinotify/github-action@main
        with:
          to: 'karim@ninjaz.ae'
          subject: 'GitHub Actions Job Status'
          body:  'Job ${{ github.job }} finished! \n \n See the results here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \n \n from: NinjazPosts App'
