name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  flutter_version: "3.19.0"

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      
      - name: Install Flutter
        id: flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' 
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:'
      
      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: dart run realm_dart install &&flutter test

      - name: Build APK
        run: flutter build apk

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: builds
          path: build/app/outputs/flutter-apk/*.apk
      
      - name: Send Email
        uses: cinotify/github-action@main
        with:
          to: 'topia.amr@icloud.com'
          subject: 'GitHub Actions Job Status'
          body:  'Job ${{ github.job }} finished! See the results here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} from: Ninja App version ${{ steps.flutter.outputs.VERSION }}'
          attachment: 'build/app/outputs/apk/release/app-release.apk'
